### ISSUE TITLE
Write test cases

### ISSUE THREAD

**Issue by gajus** [gajus/youtube-player#1]
Haven't figured out a way how to test the API when it depends on an external API without using remote scripts. Promise logic around the SDK is primitive.

**Comment by resistdesign** [comment]
@gajus You don't want to test the external APIs, just your units. So I wouldn't test anything that interacts with DOM, that's going to get sticky and you'll have to rewrite you code for a fake DOM to be injected or use a browser to execute tests. (YUCK :P)
(I guess if you really wanted to test your default export you could mock `document. getElementById ` globally and that should suffice.)

I would say at least test the 2 functions in `src/YouTubePlayer.js` by passing them some mocked objects and testing that they call some mock functionality when utilized.

**Comment by gajus** [comment]
> I would say at least test the 2 functions in src/YouTubePlayer.js by passing them some mocked objects and testing that they call some mock functionality when utilized.

PR is welcome. :-)

If you do do it, please use https://github.com/avajs/ava

**Comment by gajus** [comment]
I have given this library a facelift, https://github.com/gajus/youtube-player/tree/v4.0.0. If someone were to contribute simple unit tests, that would a welcome addition.

**Comment by resistdesign** [comment]
@gajus Does AVA have an exports interface like Mocha? https://mochajs.org/#exports

**Comment by resistdesign** [comment]
@gajus Also, what is different in 4.0.0? And are you looking for tests for the 4.0.0 branch?

**Comment by gajus** [comment]
> @gajus Also, what is different in 4.0.0? And are you looking for tests for the 4.0.0 branch?

The only difference is the addition of the [`babel-plugin-add-module-exports` transpiler](https://github.com/gajus/youtube-player/blob/48efc85b3378456eea6c31100b7db2914f84c91e/.babelrc#L5).

If you were importing this package using vanilla commonjs modules, then previously you'd have done `require('youtube-player').default`, where as now it is just `require('youtube-player')`. It is not a breaking change if you are using ES modules with `babel-plugin-transform-es2015-modules-commonjs`.

**Comment by resistdesign** [comment]
@gajus AFAIK, you only need that with `require`, not `import`. This was confusing for me at first so I really read up on it. So as far as I could tell, `import` gets the `default` export unless you destructure something specific from the module. Only with `require` would you need to do `require('something').default`. But I would really like to know, did you actually have trouble with this even when using `import`?!

**Comment by gajus** [comment]
> @gajus AFAIK, you only need that with require, not import. This was confusing for me at first so I really read up on it. So as far as I could tell, import gets the default export unless you destructure something specific from the module. Only with require would you need to do require('something').default. But I would really like to know, did you actually have trouble with this even when using import?!

That exactly what I have said:

> If you were importing this package using vanilla commonjs modules, then previously you'd have done `require('youtube-player').default`, where as now it is just `require('youtube-player')`. It is not a breaking change if you are using ES modules with `babel-plugin-transform-es2015-modules-commonjs`.

This is not a breaking change if you are using ES modules. However, there are people you continue to use commonjs with youtube-player.

**Comment by resistdesign** [comment]
Oh right, that makes sense if you are still suporting commonjs going forward, sorry :)

So you never answered me about AVA, does that have an exports interface? I might do some tests, but I really prefer the nested objects to function calls.

**Comment by gajus** [comment]
> So you never answered me about AVA, does that have an exports interface? I might do some tests, but I really prefer the nested objects to function calls.

No, it doesn't. It is considered an anti-pattern in ava.

**Comment by resistdesign** [comment]
I'm guessing I miscommunicated something because the purpose of the exports interface in mocha is to allieviate the anti pattern of describe and it. But from the looks of it, AVA doesn't have an interface for consuming and exported, nested structure rather than calling a function repeatedly. I was going to put some unit tests together, but I can't really dig into AVA right now, sorry man :(

**Comment by gajus** [comment]
> I'm guessing I miscommunicated something because the purpose of the exports interface in mocha 

I thought you are asking about being able to nest tests when you said:

> I might do some tests, but I really prefer the nested objects to function calls.

RE:

> I was going to put some unit tests together, but I can't really dig into AVA right now, sorry man :(

It is simply the matter of:

```js
import test from 'ava';

test((t) => {
  t.true(something());
});
```

**Comment by resistdesign** [comment]
If it's that simple, ok, but it looks like a lot of config is required to use AVA, no?

**Comment by gajus** [comment]
Its already configured https://github.com/gajus/youtube-player/blob/48efc85b3378456eea6c31100b7db2914f84c91e/package.json#L7-L12 :-)

**Comment by resistdesign** [comment]
Oh, ok, cool, I'll take a stab at some test then :)
