### ISSUE TITLE
How to get videoTitle?

### ISSUE THREAD

**Issue by MrAmericanMike** [gajus/youtube-player#106]
When using the Youtube API we can get the video title by using .videoTitle but I couldn't find a way to do so using this library.

Is there something I'm missing to be able to get the title?

**Comment by resistdesign** [comment]
Are you able to access it using event data?

```js
player.on('stateChange', (event) => {
    // event.data
});
```

**Comment by MrAmericanMike** [comment]
> Are you able to access it using event data?
> 
> ```js
> player.on('stateChange', (event) => {
>     // event.data
> });
> ```

No, the event "stateChange" only returns an integer as data representing the player state.

But thanks for pointing this out, logging the response made me realize that `event.target` has the information I was looking for.

`event.target.videoTitle`

Thanks a lot once again, sorry that I missed it was there.

**Comment by resistdesign** [comment]
Awesome, I'm glad you found it!!!!!
