### ISSUE TITLE
Remove Bluebird dependency

### ISSUE THREAD

**Issue by goto-bus-stop** [gajus/youtube-player#11]
Bluebird is great but a really big (20kb!! minified + gzipped) dependency to take on for browser apps, especially since many projects likely already include their own Promise polyfill. It'd be great to be able to use youtube-player without increasing bundle sizes by that amount :)

I can think of at least two ways to do this:

 1. Use the global Promise, and ask users to provide a Promise polyfill. This would be a breaking change, especially for older browsers.
 2. Avoid using Promises altogether. This would not be a breaking change, but would be more than a 5 line diff :smile:

I quite like the second option, and would be happy to send a PR for either one, but wanted to poll for feedback/opinions/ideas first :)

**Comment by gajus** [comment]
It is a big dependency and that is why you should consolidate Promise implementations in your browser build. You can do that using webpack aliases. I am sure Browserify provides a method for that too.

**Comment by goto-bus-stop** [comment]
…turns out it does. I had misunderstood Browserify's `require` alias option. Thank you, sorry for the trouble!
