### ISSUE TITLE
Getting video playback information?

### ISSUE THREAD

**Issue by SQbiz** [gajus/youtube-player#13]
Let's say I want to track the played duration of the video to update a scrubber:

```
let player;

player = YouTubePlayer('video-player');

player.loadVideoById('M7lc1UVf-VE');

player.playVideo().then(() => {
	setInterval(() => {
		console.log(player.getCurrentTime());
	}, 500)
});
```

The console returns:

![image](https://cloud.githubusercontent.com/assets/11514928/16254718/b3f74976-37f7-11e6-8aa1-8ef4e307cd3c.png)

Am I missing something?

**Comment by gajus** [comment]
`player.getCurrentTime()` returns a promise.

**Comment by SQbiz** [comment]
only just getting up to speed on promises over here - I didn't recognize the output and didn't know what to do with it -

Thanks for the quick reply!

**Comment by simonlc** [comment]
@gajus I'm curious as to why you changed it to return a promise, is it async by nature?

**Comment by gajus** [comment]
> @gajus I'm curious as to why you changed it to return a promise, is it async by nature?

No. However, method's availability is available depending on an asynchronous condition. Makes sense?

**Comment by tirithen** [comment]
The promise does not seem to return any result in the then callback :/

**Comment by gajus** [comment]
> The promise does not seem to return any result in the then callback :/

Sounds like an unrelated question/ issue. Please raise a new ticket.
