### ISSUE TITLE
NPM Page Has Broken Links

### ISSUE THREAD

**Issue by machineghost** [gajus/youtube-player#14]
Your NPM page links to your examples, but it links with URLs like:

    https://github.com/gajus/youtube-player/blob/master/examples/src/playing-video/index.html

when it should have URLs like:

    https://github.com/gajus/youtube-player/blob/master/examples/playing-video/index.html

(note the `/src`).

**Comment by gajus** [comment]
Whats the problem with https://github.com/gajus/youtube-player/blob/master/examples/src/playing-video/index.html link?

**Comment by machineghost** [comment]
Whoops, I mixed the working and the non-working URLs up.  The point is, the links here (under "Examples") aren't working:

https://www.npmjs.com/package/youtube-player

**Comment by gajus** [comment]
Thats true, however this appears to a bug belonging to https://github.com/npm organisation.

**Comment by machineghost** [comment]
You don't maintain your own project's NPM page?

**Comment by gajus** [comment]
> You don't maintain your own project's NPM page?

The markdown on the page is correct. It is the NPM that incorrectly interprets it. There is nothing that I can do about it.

**Comment by machineghost** [comment]
Ah.  I just assumed authors had more control over the page, but if not then yeah, not your bug :)
