### ISSUE TITLE
Bluebird depenency is 95% of youtube-player size...

### ISSUE THREAD

**Issue by timpler** [gajus/youtube-player#16]
```
youtube-player: 181.6 KB (9.17%)
  bluebird: 173.98 KB (95.8%)
  <self>: 7.62 KB (4.20%)
```

I was trying to optimize my bundle size with `webpack-bundle-size-analyzer` and this is what I've found. I think it's insane.

**Comment by lukejacksonn** [comment]
I think this can be marked as resolved now due to https://github.com/gajus/youtube-player/pull/17 being merged 👍

**Comment by timpler** [comment]
@lukejacksonn right ;)
