### ISSUE TITLE
3.1.0 breaking change

### ISSUE THREAD

**Issue by Munter** [gajus/youtube-player#20]
From 3.0.5 to 3.1.0 the dist files changed from using functions to using arrow functions. This is breaking our webpack build if we don't pass npm dependencies through babel (which we don't for performance reasons).

To my eyes this makes 3.1.0 a breaking change, not following semver and will most likely break setups across the board.

I assume this can be fixed by changing the babel setup for your build step so it targets browsers instead of node 4.

I recommend unpublishing 3.1.0 and releasing an update with a fix

**Comment by gajus** [comment]
Fixed in v3.1.2.

Consider switching to v4. The only breaking change is the addition of `babel-plugin-add-module-exports` (previously you needed to `require('youtube-player').default` if you are using commonjs; now it is just `require('youtube-player')`).
