### ISSUE TITLE
Non-optimizable dependency on lodash

### ISSUE THREAD

**Issue by aaugustin** [gajus/youtube-player#29]
After installing youtube-player with npm, the entrypoint is `node_modules/youtube-player/dist/index.js`, which contains the following code (generated by webpack)

```
var _lodash = require('lodash');
var _lodash2 = _interopRequireDefault(_lodash);
```

This call isn't optimizable by babel-lodash-plugin. Thus adds 700kb to my bundle -- much more than youtube-player itself!

Possible solutions include:

- using babel-lodash-plugin when compiling the library
- importing only the specific functions you need from 'lodash/...'
- including the source in releases and adding jsnext:main to package.json.

**Comment by gajus** [comment]
> using babel-lodash-plugin when compiling the library

Looks like this Plugin was overlooked when migrating from Pragmatist.

**Comment by gajus** [comment]
Done. Note that you still need to use https://github.com/lodash/lodash-webpack-plugin to ensure that all lodash dependencies are deduplicated.

**Comment by aaugustin** [comment]
Thanks for the quick response!
