### ISSUE TITLE
Commit tools

### ISSUE THREAD

**Issue by resistdesign** [gajus/youtube-player#43]
Consider setting up `commitizen` to help format commit messages: https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-writing-conventional-commits-with-commitizen

**Comment by gajus** [comment]
No. Additional headache to maintain.

If developer wants to use it, nothing stopping from setting up in a local environment.

We can use https://gitmagic.io/ if the concern is git quality.

**Comment by resistdesign** [comment]
Ok cool, makes sense :)
