### ISSUE TITLE
how do i add options

### ISSUE THREAD

**Issue by kylegoines** [gajus/youtube-player#51]
theres no docs on updated options for 

```
{
controls: 0,
rel: 0,
showInfo: 0
}
```

**Comment by resistdesign** [comment]
It should just work if you put them on the options object???

https://github.com/gajus/youtube-player#usage

**Comment by resistdesign** [comment]
@kylegoines Did that help at all?

**Comment by resistdesign** [comment]
@kylegoines I'm going to close this, just let us know if you need more help.
