### ISSUE TITLE
Dependency `babel-runtime` not listed 

### ISSUE THREAD

**Issue by markology** [gajus/youtube-player#52]
When installing plugin, needed to install `babel-runtime` in addition to `youtube-player`. Its in use within the plugin but not listed as a dependency

**Comment by resistdesign** [comment]
@markology I'm not quite sure what you mean, can you elaborate a little please?

**Comment by resistdesign** [comment]
@markology If you can just give me a little more input I'll be happy to work this out :)

**Comment by gajus** [comment]
My guess is that the `babel-preset-env` is adding `babel-runtime` to the code.

```
MacBook-Pro~/Documents/dev/gajus/youtube-player(master|✔) % ag runtime ./dist
dist/index.js
7:var _regenerator = require('babel-runtime/regenerator');
11:var _asyncToGenerator2 = require('babel-runtime/helpers/asyncToGenerator');
15:var _promise = require('babel-runtime/core-js/promise');

dist/loadYouTubeIframeApi.js
7:var _promise = require('babel-runtime/core-js/promise');

dist/YouTubePlayer.js
7:var _regenerator = require('babel-runtime/regenerator');
11:var _promise = require('babel-runtime/core-js/promise');
15:var _asyncToGenerator2 = require('babel-runtime/helpers/asyncToGenerator');

```

https://github.com/babel/babel-preset-env#exclude

If you install `youtube-player` now, `babel-runtime` does not get installed.

```
npm install --production
youtube-player@4.0.1 /Users/gajus/Documents/dev/gajus/youtube-player
├── load-script@1.0.0
├── lodash@4.17.4
```

**Comment by resistdesign** [comment]
@gajus So do we just add it as a dep???

**Comment by gajus** [comment]
Yes.

**Comment by resistdesign** [comment]
Ok

**Comment by markology** [comment]
Sorry. I didnt see these questions until now. Yes! that is the update I was looking for. thanks guys.
