### ISSUE TITLE
Example not work

### ISSUE THREAD

**Issue by jayjariwala786** [gajus/youtube-player#57]
npm run start

> @ start /Users/artoon/Downloads/youtube-player-master/examples
> webpack-dev-server

 http://127.0.0.1:8000/webpack-dev-server/
webpack result is served from /
content is served from /Users/artoon/Downloads/youtube-player-master/examples/src
Hash: c28e23aa885e857f10fd
Version: webpack 2.3.1
Time: 78ms

WARNING in webpack: Using NoErrorsPlugin is deprecated.
Use NoEmitOnErrorsPlugin instead.

ERROR in Entry module not found: Error: Can't resolve 'babel' in '/Users/artoon/Downloads/youtube-player-master/examples/src'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'babel-loader' instead of 'babel',
                 see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed

**Comment by gajus** [comment]
This is easy to fix – simply requires to update webpack configuration. PR is welcome.

**Comment by jayjariwala786** [comment]
Hey!!  i already updated webpack( 2.3.1 ) used ......

**Comment by jayjariwala786** [comment]
hello gajus, 
 
i compiled successfully but i get one error when click on playing video
can you solve this ?
index.js:37 GET https://www.youtube.com/iframe_api net::ERR_TIMED_OUT

**Comment by resistdesign** [comment]
@jayjariwala786 Please create a new issue and give us as much info as you can :)
