### ISSUE TITLE
Volume changed event

### ISSUE THREAD

**Issue by hugurp** [gajus/youtube-player#60]
hi!

it seems that an `onVolumeChange` event can be attached to the player 
see here https://github.com/videojs/videojs-youtube/blob/master/src/Youtube.js#L235
and here http://jsbin.com/ravucixoca/3/edit?html,console,output

I can't succeed doing `player.on('onVolumeChange', this.handleVolumeChange)`

any idea what I could do?

Thanks!

**Comment by gajus** [comment]
It should be a simple change to the codebase if only the event name is missing.

**Comment by oskarrough** [comment]
Great. It returns an object like this

```
{volume: 82.6923076923077, muted: false}
```

http://jsbin.com/werasumaqo/edit?html,js,output
