### ISSUE TITLE
on('stateChange') not working.

### ISSUE THREAD

**Issue by DanielHudson** [gajus/youtube-player#7]
Doesn't seem to be triggering any events - even with the example...

'ready' seems fine though?

**Comment by gajus** [comment]
It is an open source and relatively simple project. Please give it a try debugging.

**Comment by gajus** [comment]
`youtube-player@3.0.4` has been released. Thank you!

**Comment by Iambecomeroot** [comment]
I am still getting this with v5.4.0. Any suggestions?
