### ISSUE TITLE
Add typescript types declaration

### ISSUE THREAD

**Issue by ruimcf** [gajus/youtube-player#78]
I would like for this project to have a types definition in typescript, maybe published under @types/youtube-player to the [Definitely typed](https://github.com/DefinitelyTyped/DefinitelyTyped) project

Since this project already has flow types declared, maybe that will help to achieve this.

I would appreciate if I could get help to do this.

**Comment by thejaff2** [comment]
+1 on this.

**Comment by doong-jo** [comment]
Are you looking for this? 

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/youtube-player
