### ISSUE TITLE
nocookie option

### ISSUE THREAD

**Issue by vedran-brnjetic** [gajus/youtube-player#79]
I ended up here from juliussohn/react-youtube-background which uses the troybetz/react-youtube component which in fact uses this as the basis for their component. 

Can you add a possibility to use **www.youtube-nocookie.com** as the source of the video, just without cookies, to [make use of YouTube's enhanced privacy](https://www.ghacks.net/2018/05/23/why-you-should-always-use-youtubes-privacy-enhanced-mode/)? Either by default or through an optional parameter.

Thank you.

**Comment by resistdesign** [comment]
@vedran-brnjetic Are you able to pass the `host` option as suggested at this link: https://portalzine.de/dev/api/youtube-iframe-api-and-cookieless-domain-solution-gdpr-dsgvo/

**Comment by resistdesign** [comment]
@vedran-brnjetic If you could try that suggestion and let me know if we still need to add something that would be great :)

**Comment by vedran-brnjetic** [comment]
@resistdesign I will get back to you on that tomorrow. I've been sidetracked a bit this week.

**Comment by vedran-brnjetic** [comment]
@resistdesign first off, you can close this issue, the problem is in the highest level component I use.

I've finally gotten around to do some testing. Please bear in mind that I use the <YoutubeBackground> React component from juliussohn/react-youtube-background 

<YoutubeBackground> uses <YouTube> React component from troybetz/react-youtube 

YouTubePlayer is at the bottom of this chain and now I'm trying to pull the host option through the maze...

... _about an hour later_ ...

After some playing around I discovered that <YouTube> supports passing *opts* object which, if contains correct host property, works like a charm. 

Now I just need to get the <YoutubeBackground> component to support this feature. (In my private fork I did the following change to make it happen through passing the "nocookie" prop)

Using the component:

```
<YoutubeBackground videoId="mQJvyhlJZDg" nocookie>
//custom content
</YoutubeBackground>
```

Code update:
Added the following line here:
host: this.props.nocookie ? 'https://www.youtube-nocookie.com' : 'https://www.youtube.com'
```
const videoOptions = {
	playerVars: {
		autoplay: 1,
		controls: 0,
		rel: 0,
		showinfo: 0,
		mute:1
	},
        host: this.props.nocookie ? 'https://www.youtube-nocookie.com' : 'https://www.youtube.com'
};
```

So, the bottom line is, your code is good, react-youtube also supports it, update is needed to react-youtube-background code to make this work for me.

Sorry for opening the non-issue, but I didn't have time before to dig through 3 repos to find which one is not supporting the thing I need.

**Comment by resistdesign** [comment]
@vedran-brnjetic It was totally worth posting the issue, now we and future readers know that this package supports `nocookie` AND, I learned that `react-youtube-background` exists and sounds very interesting :)

Thank you for digging through all of this and verifying that it does work!
