### ISSUE TITLE
Capturing keyboard events with video selected

### ISSUE THREAD

**Issue by JoeRoddy** [gajus/youtube-player#80]
I'm attempting to give users the ability to control videos with keyboard inputs.  Just to test it out, I created document level event listener for different key presses which then execute a speed up / slow down depending on the key.

`document.addEventListener("keydown", this.handleCustomKeyEvents, false);`

I have a version that is working perfectly, **unless** the user clicks on the youtube video.  Once the video is selected,  I can no longer access the keyboard events.  I tried adding the listener to the player itself, ie:

`player.addEventListener("keydown", this.handleCustomKeyEvents, false);`
 But ^that doesn't capture the event either.

I'm not sure if this is an issue I'm having with this repo, or with iframes in general (haven't worked with iframes a ton).  Is this something that you think is possible? 
 Any tips would be appreciated.

**Comment by gajus** [comment]
Sounds like a generic question JavaScript question: How to handle keydown events once focused on iframe. Perhaps https://stackoverflow.com/questions/1199075/keydown-event-on-a-iframe ? Happy to re-open this/ merge PR if a fix is needed.
