### ISSUE TITLE
'Symbol' is undefined using Babel in IE11

### ISSUE THREAD

**Issue by vvebvvizard** [gajus/youtube-player#81]
Hi there!

I'm using Babel in my app. Since Babel does not transpile node_modules when using `useBuiltIns: 'usage'`, I have this error `'Symbol' is undefined` on IE11 when I import the youtube-player. I see a src folder in your files (with a .babelrc) but where are the dist files?

<img width="475" alt="symbol" src="https://user-images.githubusercontent.com/1065851/67056967-8e486c00-f11c-11e9-8824-7fda97353f92.png">

**Comment by gajus** [comment]
https://www.unpkg.com/browse/youtube-player@5.5.2/
