### ISSUE TITLE
Package is not published on merge of "feature" or  "chore"

### ISSUE THREAD

**Issue by zymotik** [gajus/youtube-player#89]
**A note for the maintainer/owner @gajus.** 
We have merged two pull requests ([87](https://github.com/gajus/youtube-player/pull/87) and [88](https://github.com/gajus/youtube-player/pull/88)), but the publish package action has not delivered a new package to npm. Can you help please?

_Originally posted by @zymotik in https://github.com/gajus/youtube-player/issues/88#issuecomment-1015372387_

**Comment by zymotik** [comment]
👀

**Comment by rgraffbrd** [comment]
@gajus ???

**Comment by zymotik** [comment]
I've sent an email to Gajus today in the hope I can help out with a publish action or work something else out with him.

> Hi Gajus,
> 
> We are using your package in our project. It's really useful, thank you! The latest code in the repo is a little out of date with the last release to npm over 4 years ago. Is there any way I can help with fixing this? I'd like to resolve the package release process with a github action. If you didn't mind adding a token for npm to the repo secrets, I'd happily write a publish action for github. This would resolve: https://github.com/gajus/youtube-player/issues/89
> 
> Thanks for your efforts in creating this repo,
> 
> Ian
>

**Comment by resistdesign** [comment]
@gajus !!!!!!! 😁

**Comment by gajus** [comment]
I will circle back to this before end of the day. Thank you for surfacing the issue.

**Comment by gajus** [comment]
Semantic-release releases fixed.
